[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "calc"
path = "src/calc.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
